config/routes.rb
E2gather::Application.routes.draw do
  get "e2gather/index"
  
  resources :events
  resources :users
  resources :ingredients

  root 'e2gather#index'
  
  get 'e2gather/loginFacebook' => 'e2gather#loginFacebook'
  get '/logout' =>'e2gather#logout'
  post 'e2gather/sendmail' => 'e2gather#sendmail'
  post 'e2gather/sendMessage' => 'e2gather#sendmsg'
  get 'e2gather/render_event_page' => 'e2gather#render_event_page'
  post 'e2gather/create_user_event' => 'e2gather#create_user_event'
  post 'e2gather/invite_guest' =>'e2gather#invite_guest'
  get 'e2gather/pick_guest_page/:e_id' =>'e2gather#pick_guest_page'
 
  get 'e2gather/render_ingredient_page' => 'e2gather#render_ingredient_page'
  post 'e2gather/create_ingredient' => 'e2gather#create_ingredient'
  get 'e2gather/show_ingredient/:id' => 'e2gather#show_ingredient' 
  get 'e2gather/edit_ingredient/:id' => 'e2gather#edit_ingredient' 
  patch 'e2gather/edit_ingredient/:id' => 'e2gather#update_ingredient'
  get  'e2gather/delete_ingredient/:id'=> 'e2gather#delete_ingredient' 
  delete 'e2gather/delete_ingredient/:id'=> 'e2gather#delete_ingredient'
  
  get 'events/view_event_page/:e_id' => 'events#view_event_page'
  get 'events/view_host_event_page/:e_id' => 'events#veiw_host_event_page'
  get 'events/select_guests/:e_id' => 'events#select_guests'
  post 'events/finalized' => "events#finalized"
  post 'users/update_invitation' => 'users#update_invitation'
  get 'e2gather/errorpage' => 'e2gather#errorpagenotfound'

  get 'e2gather/render_ingredient_page' => 'e2gather#render_ingredient_page'
  post 'e2gather/create_ingredient' => 'e2gather#create_ingredient'
  get ':not_found'=> 'e2gather#errorpagenotfound'
  post ':not_found' => 'e2gather#errorpagenotfound'

  

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
self.primary_key='id'
belongs_to :user
validates_presence_of :name
validates_presence_of :unit
validates :quantity, numericality: { less_than_or_equal_to: 10000, greater_than: 0}
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all 
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
    @ingredient = Ingredient.find(params[:id])
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
    @users = User.find(:all)
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ingredient }
      else
        format.html { render action: 'new' }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to 'e2gather/loginFacebook', notice: 'Ingredient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      if Ingredient.where(id: params["id"]).exists?
        @ingredient = Ingredient.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:ingredient_id, :name, :quantity, :unit, :user_id)
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :unit %><br>
    <%= f.text_field :unit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<h1>Listing ingredients</h1>

<table>
  <thead>
    <tr>
<!--      <th>Ingredient_id</th>-->
      <th>Name</th>
      <th>Quantity</th>
      <th>Unit</th>
<!--      <th>User</th>-->
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
<!--        <td><%= ingredient.ingredient_id %></td> -->
        <td><%= ingredient.name %></td>
        <td><%= ingredient.quantity %></td>
        <td><%= ingredient.unit %></td>
<!--        <td><%= ingredient.user_id %></td>-->
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { 
          confirm: 'Delete '+ingredient.name+'?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @ingredient.quantity %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @ingredient.unit %>
</p>
<!--
<p>
  <strong>User:</strong>
  <%= @ingredient.user_id %>
</p>
-->
<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>